# Yu-Gi-Oh Extra Deck Monster Card Database
# Each card is represented as a dictionary with 8 characteristics.

extra_deck_fusions_cards = [
    { # Charubin the Fire Knight
        "Name": "Charubin the Fire Knight",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "FIRE",
        "Level": 3,
        "Type": "Pyro, Fusion, Normal",
        "Materials": "Monster Egg + Hinotama Soul",
        "Effect": "None",
        "ATK": 1100,
        "DEF": 800
    },
    { # Darkfire Dragon
        "Name": "Darkfire Dragon",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Dragon, Fusion, Normal",
        "Materials": "Firegrass + Petit Dragon",
        "Effect": "None",
        "ATK": 1500,
        "DEF": 1250
    },
    { # Fusionist
        "Name": "Fusionist",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Beast, Fusion, Normal",
        "Materials": "Petit Angel + Mystical Sheep #2",
        "Effect": "None",
        "ATK": 900,
        "DEF": 700
    },
    { # Dragoness the Wicked Knight
        "Name": "Dragoness the Wicked Knight",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "WIND",
        "Level": 3,
        "Type": "Warrior, Fusion, Normal",
        "Materials": "Armaill + One-Eyed Shield Dragon",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900
    },
    { # Gaia the Dragon Champion
        "Name": "Gaia the Dragon Champion",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "EARTH",
        "Level": 7,
        "Type": "Warrior, Fusion, Normal",
        "Materials": "Gaia The Fierce Knight + Curse of Dragon",
        "Effect": "None",
        "ATK": 2600,
        "DEF": 2100
    },
    { # Flame Ghost
        "Name": "Flame Ghost",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Zombie, Fusion, Normal",
        "Materials": "Skull Servant + Dissolverock",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 800
    },
    { # Flower Wolf
        "Name": "Flower Wolf",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Beast, Fusion, Normal",
        "Materials": "Silver Fang + Darkworld Thorns",
        "Effect": "None",
        "ATK": 1800,
        "DEF": 1400
    },
    { # Karbonala Warrior
        "Name": "Karbonala Warrior",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Fusion, Normal",
        "Materials": "M-Warrior #1 + M-Warrior #2",
        "Effect": "None",
        "ATK": 1500,
        "DEF": 1200
    },
    { # Metal Dragon
        "Name": "Metal Dragon",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "WIND",
        "Level": 6,
        "Type": "Machine, Fusion, Normal",
        "Materials": "Steel Ogre Grotto #1 + Lesser Dragon",
        "Effect": "None",
        "ATK": 1850,
        "DEF": 1700
    },
    { # Flame Swordsman
        "Name": "Flame Swordsman",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "FIRE",
        "Level": 5,
        "Type": "Warrior, Fusion, Normal",
        "Materials": "Flame Manipulator + Masaki the Legendary Swordsman",
        "Effect": "None",
        "ATK": 1800,
        "DEF": 1600
    },
    { # Black Skull Dragon
        "Name": "Black Skull Dragon",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 9,
        "Type": "Dragon, Fusion, Normal",
        "Materials": "Summoned Skull + Red-Eyes Black Dragon\n(This card is always treated as an 'Archfiend' card.)",
        "Effect": "None",
        "ATK": 3200,
        "DEF": 2500
    },
    { # Twin-Headed Thunder Dragon
        "Name": "Twin-Headed Thunder Dragon",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "LIGHT",
        "Level": 7,
        "Type": "Thunder, Fusion, Normal",
        "Materials": "Thunder Dragon + Thunder Dragon",
        "Effect": "None",
        "ATK": 2800,
        "DEF": 2100
    },
    { # Bickuribox
        "Name": "Bickuribox",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Fiend, Fusion, Normal",
        "Materials": "'Crass Clown' + 'Dream Clown'",
        "Effect": "None",
        "ATK": 2300,
        "DEF": 2000
    },
    { # Cyber Saurus
        "Name": "Cyber Saurus",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Machine, Fusion, Normal",
        "Materials": "'Blast Juggler' + 'Two-Headed King Rex'",
        "Effect": "None",
        "ATK": 1800,
        "DEF": 1400
    },
    { # Deepsea Shark
        "Name": "Deepsea Shark",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "WATER",
        "Level": 5,
        "Type": "Fish, Fusion, Normal",
        "Materials": '"Bottom Dweller" + "Tongyo"',
        "Effect": "None",
        "ATK": 1900,
        "DEF": 1600
    },
    { # Empress Judge
        "Name": "Empress Judge",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "EARTH",
        "Level": 6,
        "Type": "Warrior, Fusion, Normal",
        "Materials": "'Queen's Double' + 'Hibikime'",
        "Effect": "None",
        "ATK": 2100,
        "DEF": 1700
    },
    { # Giltia the D. Knight
        "Name": "Giltia the D. Knight",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "LIGHT",
        "Level": 5,
        "Type": "Warrior, Fusion, Normal",
        "Materials": '"Guardian of the Labyrinth" + "Protector of the Throne"',
        "Effect": "None",
        "ATK": 1850,
        "DEF": 1500
    },
    { # Kaminari Attack
        "Name": "Kaminari Attack",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "WIND",
        "Level": 5,
        "Type": "Thunder, Fusion, Normal",
        "Materials": '"Ocubeam" + "Mega Thunderball"',
        "Effect": "None",
        "ATK": 1900,
        "DEF": 1400
    },
    { # Labyrinth Tank
        "Name": "Labyrinth Tank",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Machine, Fusion, Normal",
        "Materials": "'Giga-Tech Wolf' + 'Cannon Soldier'",
        "Effect": "None",
        "ATK": 2400,
        "DEF": 2400
    },
    { # Musician King
        "Name": "Musician King",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "LIGHT",
        "Level": 5,
        "Type": "Spellcaster, Fusion, Normal",
        "Materials": "'Witch of the Black Forest' + 'Lady of Faith'",
        "Effect": "None",
        "ATK": 1750,
        "DEF": 1500
    },
    { # Punished Eagle
        "Name": "Punished Eagle",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "WIND",
        "Level": 6,
        "Type": "Winged Beast, Fusion, Normal",
        "Materials": '"Blue-Winged Crown" + "Niwatori"',
        "Effect": "None",
        "ATK": 2100,
        "DEF": 1800
    },
    { # Rabid Horseman
        "Name": "Rabid Horseman",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "EARTH",
        "Level": 6,
        "Type": "Beast-Warrior, Fusion, Normal",
        "Materials": "'Battle Ox' + 'Mystic Horseman'",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 1700
    },
    { # Roaring Ocean Snake
        "Name": "Roaring Ocean Snake",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "WATER",
        "Level": 6,
        "Type": "Aqua, Fusion, Normal",
        "Materials": '"Mystic Lamp" + "Hyosube"',
        "Effect": "None",
        "ATK": 2100,
        "DEF": 1800
    },
    { # Skull Knight
        "Name": "Skull Knight",
        "Category": "Monster",
        "Extra Deck Type": "Fusion",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Spellcaster, Fusion, Normal",
        "Materials": '"Tainted Wisdom" + "Ancient Brain"',
        "Effect": "None",
        "ATK": 2650,
        "DEF": 2250
    },
    # Add more cards below using the same format
]