# Yu-Gi-Oh Vanilla Monster Card Database
# Each card is represented as a dictionary with 7 characteristics.

vanilla_monster_cards = [
    { #Blue-Eyes White Dragon
        "Name": "Blue-Eyes White Dragon",
        "Attribute": "LIGHT",
        "Level": 8,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 3000,
        "DEF": 2500,
    },
    { #Dark Magician
        "Name": "Dark Magician",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 2500,
        "DEF": 2100,
    },
    { #Summoned Skull
        "Name": "Summoned Skull",
        "Attribute": "DARK",
        "Level": 6,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 2500,
        "DEF": 1200,
    },
    { #Aqua Madoor
        "Name": "Aqua Madoor",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 2000,
    },
    { #Giant Soldier of Stone
        "Name": "Giant Soldier of Stone",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 2000,
    },
    { #Spirit of the Harp
        "Name": "Spirit of the Harp",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 2000,
    },
    { #Gaia The Fierce Knight
        "Name": "Gaia The Fierce Knight",
        "Attribute": "EARTH",
        "Level": 7,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 2300,
        "DEF": 2100,
    },
    { #Left Arm of the Forbidden One
        "Name": "Left Arm of the Forbidden One",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { #Left Leg of the Forbidden One
        "Name": "Left Leg of the Forbidden One",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { #Right Arm of the Forbidden One
        "Name": "Right Arm of the Forbidden One",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { #Right Leg of the Forbidden One
        "Name": "Right Leg of the Forbidden One",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { #Red-Eyes Black Dragon
        "Name": "Red-Eyes Black Dragon",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2400,
        "DEF": 2000,
    },
    { #Celtic Guardian
        "Name": "Celtic Guardian",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1200,
    },
    { #Curse of Dragon
        "Name": "Curse of Dragon",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 1500,
    },
    { #Mystical Elf
        "Name": "Mystical Elf",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 2000,
    },
    { #Tri-Horned Dragon
        "Name": "Tri-Horned Dragon",
        "Attribute": "DARK",
        "Level": 8,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2850,
        "DEF": 2350,
    },
    { #Hinotama Soul
        "Name": "Hinotama Soul",
        "Attribute": "FIRE",
        "Level": 2,
        "Type": "Pyro, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 500,
    },
    { #Monster Egg
        "Name": "Monster Egg",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 900,
    },
    # Add more cards below using the same format
]

# Yu-Gi-Oh Effect Monster Card Database
# Each card is represented as a dictionary with 7 characteristics.

effect_monster_cards = [
    {
        "Name": "Man-Eater Bug",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Insect, Flip, Effect",
        "Effect": "FLIP: Target 1 monster on the field; destroy it",
        "ATK": 450,
        "DEF": 600
    },
    # Add more cards below using the same format
]