# Yu-Gi-Oh Vanilla Monster Card Database
# Each card is represented as a dictionary with 8 characteristics.

vanilla_monster_cards = [
    { # Blue-Eyes White Dragon
        "Name": "Blue-Eyes White Dragon",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 8,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 3000,
        "DEF": 2500,
    },
    { # Dark Magician
        "Name": "Dark Magician",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 2500,
        "DEF": 2100,
    },
    { # Summoned Skull
        "Name": "Summoned Skull",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 6,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 2500,
        "DEF": 1200,
    },
    { # Aqua Madoor
        "Name": "Aqua Madoor",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 2000,
    },
    { # Giant Soldier of Stone
        "Name": "Giant Soldier of Stone",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 2000,
    },
    { # Spirit of the Harp
        "Name": "Spirit of the Harp",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 2000,
    },
    { # Gaia The Fierce Knight
        "Name": "Gaia The Fierce Knight",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 7,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 2300,
        "DEF": 2100,
    },
    { # Left Arm of the Forbidden One
        "Name": "Left Arm of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Left Leg of the Forbidden One
        "Name": "Left Leg of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Right Arm of the Forbidden One
        "Name": "Right Arm of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Right Leg of the Forbidden One
        "Name": "Right Leg of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Red-Eyes Black Dragon
        "Name": "Red-Eyes Black Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2400,
        "DEF": 2000,
    },
    { # Celtic Guardian
        "Name": "Celtic Guardian",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1200,
    },
    { # Curse of Dragon
        "Name": "Curse of Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 1500,
    },
    { # Mystical Elf
        "Name": "Mystical Elf",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 2000,
    },
    { # Tri-Horned Dragon
        "Name": "Tri-Horned Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 8,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2850,
        "DEF": 2350,
    },
    { # Hinotama Soul
        "Name": "Hinotama Soul",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 2,
        "Type": "Pyro, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 500,
    },
    { # Monster Egg
        "Name": "Monster Egg",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 900,
    },
    { # Armaill
        "Name": "Armaill",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 1300,
    },
    { # Armored Starfish
        "Name": "Armored Starfish",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 850,
        "DEF": 1400,
    },
    { # Basic Insect
        "Name": "Basic Insect",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Insect, Normal",
        "Effect": "None",
        "ATK": 500,
        "DEF": 700,
    },
    { # Beaver Warrior
        "Name": "Beaver Warrior",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1500,
    },
    { # Dark Gray
        "Name": "Dark Gray",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 900,
    },
    { # Dark King of the Abyss
        "Name": "Dark King of the Abyss",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 800,
    },
    { # Darkworld Thorns
        "Name": "Darkworld Thorns",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900,
    },
    { # Dissolverock
        "Name": "Dissolverock",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 1000,
    },
    { # Drooling Lizard
        "Name": "Drooling Lizard",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Reptile, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 800,
    },
    { # Enchanting Mermaid
        "Name": "Enchanting Mermaid",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Fish, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900,
    },
    { # Fiend Reflection #2
        "Name": "Fiend Reflection #2",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1100,
        "DEF": 1400,
    },
    { # Firegrass
        "Name": "Firegrass",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 600,
    },
    { # Fireyarou
        "Name": "Fireyarou",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 4,
        "Type": "Pyro, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 1000,
    },
    { # Flame Manipulator
        "Name": "Flame Manipulator",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 3,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 1000,
    },
    { # Frenzied Panda
        "Name": "Frenzied Panda",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1000,
    },
    { # Green Phantom King
        "Name": "Green Phantom King",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 500,
        "DEF": 1600,
    },
    { # Hard Armor
        "Name": "Hard Armor",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 300,
        "DEF": 1200,
    },
    { # Hitotsu-Me Giant
        "Name": "Hitotsu-Me Giant",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast-Warrior, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1000,
    },
    { # Kagemusha of the Blue Flame
        "Name": "Kagemusha of the Blue Flame",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 400,
    },
    { # King Fog
        "Name": "King Fog",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 900,
    },
    { # Kumootoko
        "Name": "Kumootoko",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Insect, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 1400,
    },
    { # Kurama
        "Name": "Kurama",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 3,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 800,
    },
    { # Larvas
        "Name": "Larvas",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 1000,
    },
    { # Lesser Dragon
        "Name": "Lesser Dragon",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1000,
    },
    { # M-Warrior #1
        "Name": "M-Warrior #1",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 500,
    },
    { # M-Warrior #2
        "Name": "M-Warrior #2",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 500,
        "DEF": 1000,
    },
    { # Mammoth Graveyard
        "Name": "Mammoth Graveyard",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Dinosaur, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 800,
    },
    { # Man Eater
        "Name": "Man Eater",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 600,
    },
    { # Masaki the Legendary Swordsman
        "Name": "Masaki the Legendary Swordsman",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1100,
        "DEF": 1100,
    },
    { # Meda Bat
        "Name": "Meda Bat",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 400,
    },
    { # Misairuzame
        "Name": "Misairuzame",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Fish, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1600,
    },
    { # Mystical Sheep #2
        "Name": "Mystical Sheep #2",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 1000,
    },
    { # Nemuriko
        "Name": "Nemuriko",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 700,
    },
    { # One-Eyed Shield Dragon
        "Name": "One-Eyed Shield Dragon",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 3,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 1300,
    },
    { # Petit Angel
        "Name": "Petit Angel",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 900,
    },
    { # Petit Dragon
        "Name": "Petit Dragon",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 2,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 700,
    },
    { # Ray & Temperature
        "Name": "Ray & Temperature",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 1000,
    },
    { # Root Water
        "Name": "Root Water",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Fish, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 800,
    },
    { # Sand Stone
        "Name": "Sand Stone",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 1600,
    },
    { # Silver Fang
        "Name": "Silver Fang",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 800,
    },
    { # Skull Red Bird
        "Name": "Skull Red Bird",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1550,
        "DEF": 1200,
    },
    { # Skull Servant
        "Name": "Skull Servant",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Zombie, Normal",
        "Effect": "None",
        "ATK": 300,
        "DEF": 200,
    },
    { # Spike Seadra
        "Name": "Spike Seadra",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 5,
        "Type": "Sea Serpent, Normal",
        "Effect": "None",
        "ATK": 1600,
        "DEF": 1300,
    },
    { # Steel Ogre Grotto #1
        "Name": "Steel Ogre Grotto #1",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1800,
    },
    { # Succubus Knight
        "Name": "Succubus Knight",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1650,
        "DEF": 1300,
    },
    { # Terra the Terrible
        "Name": "Terra the Terrible",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1300,
    },
    { # The 13th Grave
        "Name": "The 13th Grave",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Zombie, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900,
    },
    { # The Furious Sea King
        "Name": "The Furious Sea King",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 700,
    },
    { # Trial of Nightmare
        "Name": "Trial of Nightmare",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 900,
    },
    { # Tripwire Beast
        "Name": "Tripwire Beast",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Thunder, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1300,
    },
    { # Turtle Tiger
        "Name": "Turtle Tiger",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 1500,
    },
    { # Two-Mouth Darkruler
        "Name": "Two-Mouth Darkruler",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Dinosaur, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 700,
    },
    { # Tyhone
        "Name": "Tyhone",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1400,
    },
    { # Uraby
        "Name": "Uraby",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Dinosaur, Normal",
        "Effect": "None",
        "ATK": 1500,
        "DEF": 800,
    },
    { # Witty Phantom
        "Name": "Witty Phantom",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1300,
    },
    { # Slot Machine
        "Name": "Slot Machine",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 2300,
    },
    # Add more cards below using the same format
]

# Yu-Gi-Oh Effect Monster Card Database
# Each card is represented as a dictionary with 8 characteristics.

effect_monster_cards = [
    { # Man-Eater Bug
        "Name": "Man-Eater Bug",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Insect, Flip, Effect",
        "Effect": "FLIP: Target 1 monster on the field; destroy it",
        "ATK": 450,
        "DEF": 600
    },
    { # Armed Ninja
        "Name": "Armed Ninja",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 1,
        "Type": "Warrior, Flip, Effect",
        "Effect": "FLIP: Target 1 Spell Card on the field; destroy that target. " \
        "(If the target is Set, reveal it, and destroy it if it is a Spell Card. Otherwise, return it to its original position.)",
        "ATK": 300,
        "DEF": 300
    },
    { # Hane-Hane
        "Name": "Hane-Hane",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Beast, Flip, Effect",
        "Effect": "FLIP: Select 1 monster on the field and return it to its owner's hand.",
        "ATK": 450,
        "DEF": 500
    },
    { # Reaper of the Cards
        "Name": "Reaper of the Cards",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Fiend, Flip, Effect",
        "Effect": "FLIP: Select 1 Trap Card on the field and destroy it. If the selected card is Set, pick up and see the card. "\
        "If it is a Trap Card, it is destroyed. If it is a Spell Card, return it to its original position.",
        "ATK": 1380,
        "DEF": 1930
    },
    { # Exodia the Forbidden One
        "Name": "Exodia the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Spellcaster, Flip, Effect",
        "Effect": "If you have 'Right Leg of the Forbidden One', 'Left Leg of the Forbidden One', 'Right Arm of the Forbidden One' and " \
        "'Left Arm of the Forbidden One' in addition to this card in your hand, you win the Duel.",
        "ATK": 1000,
        "DEF": 1000
    },
    { # Jigen Bakudan
        "Name": "Jigen Bakudan",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 2,
        "Type": "Pyro, Flip, Effect",
        "Effect": "FLIP: After this card is flipped, Tribute it during your Standby Phase to destroy all monsters you control and " \
        "inflict damage equal to half of the total ATK of the destroyed cards (excluding this monster) to your opponent.",
        "ATK": 200,
        "DEF": 1000
    },
    { # Banisher of the Light
        "Name": "Banisher of the Light",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Fairy, Effect",
        "Effect": "Any card sent to the Graveyard is banished instead.",
        "ATK": 100,
        "DEF": 2000
    },
    { # Maha Vailo
        "Name": "Maha Vailo",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Spellcaster, Effect",
        "Effect": "This card gains 500 ATK for each Equip Card equipped to this card.",
        "ATK": 1550,
        "DEF": 1400
    },
    { # Invader of the Throne
        "Name": "Invader of the Throne",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Flip, Effect",
        "Effect": "FLIP: Select 1 monster on your opponent's side of the field and switch control of it with this card. " \
        "This effect cannot be activated during the Battle Phase.",
        "ATK": 1350,
        "DEF": 1700
    },
    { # Relinquished
        "Name": "Relinquished",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Ritual, Effect",
        "Effect": "You can Ritual Summon this card with 'Black Illusion Ritual'. Once per turn: You can target 1 monster your " \
        "opponent controls; equip that target to this card (max. 1). This card's ATK/DEF become equal to that equipped monster's. " \
        "If this card would be destroyed by battle, destroy that equipped monster instead. While equipped with that monster, " \
        "any battle damage you take from battles involving this card inflicts equal effect damage to your opponent.",
        "ATK": 0,
        "DEF": 0
    },
    { # Toon Mermaid
        "Name": "Toon Mermaid",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Toon, Effect",
        "Effect": "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand), while you control 'Toon World'. " \
        "Cannot attack the turn it is Special Summoned. You must pay 500 LP to declare an attack with this monster. If 'Toon World' on " \
        "the field is destroyed, destroy this card. Can attack your opponent directly, unless they control a Toon monster, in which case this card must target a Toon monster for its attacks.",
        "ATK": 1400,
        "DEF": 1500
    },
    { # Toon Summoned Skull
        "Name": "Toon Summoned Skull",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 6,
        "Type": "Fiend, Toon, Effect",
        "Effect": "(This card is always treated as an 'Archfiend' card.) Cannot be Normal Summoned/Set. Must first be Special Summoned " \
        "(from your hand) by Tributing 1 monster, while you control 'Toon World'. Cannot attack the turn it is Special Summoned. " \
        "You must pay 500 LP to declare an attack with this monster. If 'Toon World' on the field is destroyed, destroy this card. " \
        "Can attack your opponent directly, unless they control a Toon monster, in which case this card must target a Toon monster for its attacks.",
        "ATK": 1550,
        "DEF": 1400
    },
    # Add more cards below using the same format
]