# Yu-Gi-Oh Vanilla Monster Card Database
# Each card is represented as a dictionary with 8 characteristics.

vanilla_monster_cards = [
    { # Blue-Eyes White Dragon
        "Name": "Blue-Eyes White Dragon",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 8,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 3000,
        "DEF": 2500,
    },
    { # Dark Magician
        "Name": "Dark Magician",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 2500,
        "DEF": 2100,
    },
    { # Summoned Skull
        "Name": "Summoned Skull",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 6,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 2500,
        "DEF": 1200,
    },
    { # Aqua Madoor
        "Name": "Aqua Madoor",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 2000,
    },
    { # Giant Soldier of Stone
        "Name": "Giant Soldier of Stone",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 2000,
    },
    { # Spirit of the Harp
        "Name": "Spirit of the Harp",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 2000,
    },
    { # Gaia The Fierce Knight
        "Name": "Gaia The Fierce Knight",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 7,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 2300,
        "DEF": 2100,
    },
    { # Left Arm of the Forbidden One
        "Name": "Left Arm of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Left Leg of the Forbidden One
        "Name": "Left Leg of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Right Arm of the Forbidden One
        "Name": "Right Arm of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Right Leg of the Forbidden One
        "Name": "Right Leg of the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 200,
        "DEF": 300,
    },
    { # Red-Eyes Black Dragon
        "Name": "Red-Eyes Black Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2400,
        "DEF": 2000,
    },
    { # Celtic Guardian
        "Name": "Celtic Guardian",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1200,
    },
    { # Curse of Dragon
        "Name": "Curse of Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 1500,
    },
    { # Mystical Elf
        "Name": "Mystical Elf",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 2000,
    },
    { # Tri-Horned Dragon
        "Name": "Tri-Horned Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 8,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2850,
        "DEF": 2350,
    },
    { # Hinotama Soul
        "Name": "Hinotama Soul",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 2,
        "Type": "Pyro, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 500,
    },
    { # Monster Egg
        "Name": "Monster Egg",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 900,
    },
    { # Armaill
        "Name": "Armaill",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 1300,
    },
    { # Armored Starfish
        "Name": "Armored Starfish",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 850,
        "DEF": 1400,
    },
    { # Basic Insect
        "Name": "Basic Insect",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Insect, Normal",
        "Effect": "None",
        "ATK": 500,
        "DEF": 700,
    },
    { # Beaver Warrior
        "Name": "Beaver Warrior",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1500,
    },
    { # Dark Gray
        "Name": "Dark Gray",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 900,
    },
    { # Dark King of the Abyss
        "Name": "Dark King of the Abyss",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 800,
    },
    { # Darkworld Thorns
        "Name": "Darkworld Thorns",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900,
    },
    { # Dissolverock
        "Name": "Dissolverock",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 1000,
    },
    { # Drooling Lizard
        "Name": "Drooling Lizard",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Reptile, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 800,
    },
    { # Enchanting Mermaid
        "Name": "Enchanting Mermaid",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Fish, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900,
    },
    { # Fiend Reflection #2
        "Name": "Fiend Reflection #2",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1100,
        "DEF": 1400,
    },
    { # Firegrass
        "Name": "Firegrass",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 600,
    },
    { # Fireyarou
        "Name": "Fireyarou",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 4,
        "Type": "Pyro, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 1000,
    },
    { # Flame Manipulator
        "Name": "Flame Manipulator",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 3,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 1000,
    },
    { # Frenzied Panda
        "Name": "Frenzied Panda",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1000,
    },
    { # Green Phantom King
        "Name": "Green Phantom King",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 500,
        "DEF": 1600,
    },
    { # Hard Armor
        "Name": "Hard Armor",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 300,
        "DEF": 1200,
    },
    { # Hitotsu-Me Giant
        "Name": "Hitotsu-Me Giant",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast-Warrior, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1000,
    },
    { # Kagemusha of the Blue Flame
        "Name": "Kagemusha of the Blue Flame",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 400,
    },
    { # King Fog
        "Name": "King Fog",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 900,
    },
    { # Kumootoko
        "Name": "Kumootoko",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Insect, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 1400,
    },
    { # Kurama
        "Name": "Kurama",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 3,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 800,
    },
    { # Larvas
        "Name": "Larvas",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 1000,
    },
    { # Lesser Dragon
        "Name": "Lesser Dragon",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1000,
    },
    { # M-Warrior #1
        "Name": "M-Warrior #1",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 500,
    },
    { # M-Warrior #2
        "Name": "M-Warrior #2",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 500,
        "DEF": 1000,
    },
    { # Mammoth Graveyard
        "Name": "Mammoth Graveyard",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Dinosaur, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 800,
    },
    { # Man Eater
        "Name": "Man Eater",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Plant, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 600,
    },
    { # Masaki the Legendary Swordsman
        "Name": "Masaki the Legendary Swordsman",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1100,
        "DEF": 1100,
    },
    { # Meda Bat
        "Name": "Meda Bat",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 400,
    },
    { # Misairuzame
        "Name": "Misairuzame",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Fish, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1600,
    },
    { # Mystical Sheep #2
        "Name": "Mystical Sheep #2",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 1000,
    },
    { # Nemuriko
        "Name": "Nemuriko",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Spellcaster, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 700,
    },
    { # One-Eyed Shield Dragon
        "Name": "One-Eyed Shield Dragon",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 3,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 700,
        "DEF": 1300,
    },
    { # Petit Angel
        "Name": "Petit Angel",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 900,
    },
    { # Petit Dragon
        "Name": "Petit Dragon",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 2,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 600,
        "DEF": 700,
    },
    { # Ray & Temperature
        "Name": "Ray & Temperature",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 1000,
    },
    { # Root Water
        "Name": "Root Water",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Fish, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 800,
    },
    { # Sand Stone
        "Name": "Sand Stone",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 1600,
    },
    { # Silver Fang
        "Name": "Silver Fang",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 800,
    },
    { # Skull Red Bird
        "Name": "Skull Red Bird",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1550,
        "DEF": 1200,
    },
    { # Skull Servant
        "Name": "Skull Servant",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Zombie, Normal",
        "Effect": "None",
        "ATK": 300,
        "DEF": 200,
    },
    { # Spike Seadra
        "Name": "Spike Seadra",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 5,
        "Type": "Sea Serpent, Normal",
        "Effect": "None",
        "ATK": 1600,
        "DEF": 1300,
    },
    { # Steel Ogre Grotto #1
        "Name": "Steel Ogre Grotto #1",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1800,
    },
    { # Succubus Knight
        "Name": "Succubus Knight",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Warrior, Normal",
        "Effect": "None",
        "ATK": 1650,
        "DEF": 1300,
    },
    { # Terra the Terrible
        "Name": "Terra the Terrible",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1300,
    },
    { # The 13th Grave
        "Name": "The 13th Grave",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Zombie, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 900,
    },
    { # The Furious Sea King
        "Name": "The Furious Sea King",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 700,
    },
    { # Trial of Nightmare
        "Name": "Trial of Nightmare",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1300,
        "DEF": 900,
    },
    { # Tripwire Beast
        "Name": "Tripwire Beast",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Thunder, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1300,
    },
    { # Turtle Tiger
        "Name": "Turtle Tiger",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1000,
        "DEF": 1500,
    },
    { # Two-Mouth Darkruler
        "Name": "Two-Mouth Darkruler",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Dinosaur, Normal",
        "Effect": "None",
        "ATK": 900,
        "DEF": 700,
    },
    { # Tyhone
        "Name": "Tyhone",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 1400,
    },
    { # Uraby
        "Name": "Uraby",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Dinosaur, Normal",
        "Effect": "None",
        "ATK": 1500,
        "DEF": 800,
    },
    { # Witty Phantom
        "Name": "Witty Phantom",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1300,
    },
    { # Slot Machine
        "Name": "Slot Machine",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 2300,
    },
    { # Hyozanryu
        "Name": "Hyozanryu",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 7,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2100,
        "DEF": 2800,
    },
    { # Serpent Night Dragon
        "Name": "Serpent Night Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2350,
        "DEF": 2400,
    },
    { # Ancient One of the Deep Forest
        "Name": "Ancient One of the Deep Forest",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 6,
        "Type": "Beast, Normal",
        "Effect": "None",
        "ATK": 1800,
        "DEF": 1900,
    },
    { # Dark Witch
        "Name": "Dark Witch",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 5,
        "Type": "Fairy, Normal",
        "Effect": "None",
        "ATK": 1800,
        "DEF": 1700,
    },
    { # Fire Kraken
        "Name": "Fire Kraken",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1600,
        "DEF": 1500,
    },
    { # Giant Turtle Who Feeds on Flames
        "Name": "Giant Turtle Who Feeds on Flames",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 5,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1800,
    },
    { # Guardian of the Throne Room
        "Name": "Guardian of the Throne Room",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 1650,
        "DEF": 1600,
    },
    { # High Tide Gyojin
        "Name": "High Tide Gyojin",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1650,
        "DEF": 1300,
    },
    { # Labyrinth Wall
        "Name": "Labyrinth Wall",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 0,
        "DEF": 3000,
    },
    { # Liquid Beast
        "Name": "Liquid Beast",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 950,
        "DEF": 800,
    },
    { # Mechanical Snail
        "Name": "Mechanical Snail",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 800,
        "DEF": 1000,
    },
    { # Metal Fish
        "Name": "Metal Fish",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 5,
        "Type": "Machine, Normal",
        "Effect": "None",
        "ATK": 1600,
        "DEF": 1900,
    },
    { # Octoberser
        "Name": "Octoberser",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 5,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1600,
        "DEF": 1400,
    },
    { # Peacock
        "Name": "Peacock",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 5,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1700,
        "DEF": 1500,
    },
    { # Psychic Kappa
        "Name": "Psychic Kappa",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 2,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 400,
        "DEF": 1000,
    },
    { # Queen Bird
        "Name": "Queen Bird",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 5,
        "Type": "Winged Beast, Normal",
        "Effect": "None",
        "ATK": 1200,
        "DEF": 2000,
    },
    { # Red Archery Girl
        "Name": "Red Archery Girl",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 1400,
        "DEF": 1500,
    },
    { # Ryu-Ran
        "Name": "Ryu-Ran",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 7,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 2200,
        "DEF": 2600,
    },
    { # Stone Ogre Grotto
        "Name": "Stone Ogre Grotto",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 5,
        "Type": "Rock, Normal",
        "Effect": "None",
        "ATK": 1600,
        "DEF": 1500,
    },
    { # Twin Long Rods #2
        "Name": "Twin Long Rods #2",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Aqua, Normal",
        "Effect": "None",
        "ATK": 850,
        "DEF": 700,
    },
    { # Tyhone #2
        "Name": "Tyhone #2",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 6,
        "Type": "Dragon, Normal",
        "Effect": "None",
        "ATK": 1700,
        "DEF": 1900,
    },
    { # Whiptail Crow
        "Name": "Whiptail Crow",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Normal",
        "Effect": "None",
        "ATK": 1650,
        "DEF": 1600,
    },
    { # Crab Turtle
        "Name": "Crab Turtle",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 8,
        "Type": "Aqua, Ritual",
        "Effect": "None",
        "ATK": 2250,
        "DEF": 2500,
    },
    { # Hungry Burger
        "Name": "Hungry Burger",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 6,
        "Type": "Warrior, Ritual",
        "Effect": "None",
        "ATK": 2000,
        "DEF": 1850,
    },
    { # Performance of Sword
        "Name": "Performance of Sword",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 6,
        "Type": "Warrior, Ritual",
        "Effect": "None",
        "ATK": 1950,
        "DEF": 1850,
    },
    # Add more cards below using the same format
]

# Yu-Gi-Oh Effect Monster Card Database
# Each card is represented as a dictionary with 8 characteristics.

effect_monster_cards = [
    { # Man-Eater Bug
        "Name": "Man-Eater Bug",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Insect, Flip, Effect",
        "Effect": "FLIP: Target 1 monster on the field; destroy it.",
        "ATK": 450,
        "DEF": 600
    },
    { # Armed Ninja
        "Name": "Armed Ninja",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 1,
        "Type": "Warrior, Flip, Effect",
        "Effect": "FLIP: Target 1 Spell Card on the field; destroy that target. " \
        "(If the target is Set, reveal it, and destroy it if it is a Spell Card. Otherwise, return it to its original position.)",
        "ATK": 300,
        "DEF": 300
    },
    { # Hane-Hane
        "Name": "Hane-Hane",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Beast, Flip, Effect",
        "Effect": "FLIP: Select 1 monster on the field and return it to its owner's hand.",
        "ATK": 450,
        "DEF": 500
    },
    { # Reaper of the Cards
        "Name": "Reaper of the Cards",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Fiend, Flip, Effect",
        "Effect": "FLIP: Select 1 Trap Card on the field and destroy it. If the selected card is Set, pick up and see the card. "\
        "If it is a Trap Card, it is destroyed. If it is a Spell Card, return it to its original position.",
        "ATK": 1380,
        "DEF": 1930
    },
    { # Exodia the Forbidden One
        "Name": "Exodia the Forbidden One",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Spellcaster, Flip, Effect",
        "Effect": "If you have 'Right Leg of the Forbidden One', 'Left Leg of the Forbidden One', 'Right Arm of the Forbidden One' and " \
        "'Left Arm of the Forbidden One' in addition to this card in your hand, you win the Duel.",
        "ATK": 1000,
        "DEF": 1000
    },
    { # Jigen Bakudan
        "Name": "Jigen Bakudan",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 2,
        "Type": "Pyro, Flip, Effect",
        "Effect": "FLIP: After this card is flipped, Tribute it during your Standby Phase to destroy all monsters you control and " \
        "inflict damage equal to half of the total ATK of the destroyed cards (excluding this monster) to your opponent.",
        "ATK": 200,
        "DEF": 1000
    },
    { # Banisher of the Light
        "Name": "Banisher of the Light",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Fairy, Effect",
        "Effect": "Any card sent to the Graveyard is banished instead.",
        "ATK": 100,
        "DEF": 2000
    },
    { # Maha Vailo
        "Name": "Maha Vailo",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Spellcaster, Effect",
        "Effect": "This card gains 500 ATK for each Equip Card equipped to this card.",
        "ATK": 1550,
        "DEF": 1400
    },
    { # Invader of the Throne
        "Name": "Invader of the Throne",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Warrior, Flip, Effect",
        "Effect": "FLIP: Select 1 monster on your opponent's side of the field and switch control of it with this card. " \
        "This effect cannot be activated during the Battle Phase.",
        "ATK": 1350,
        "DEF": 1700
    },
    { # Relinquished
        "Name": "Relinquished",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 1,
        "Type": "Spellcaster, Ritual, Effect",
        "Effect": "You can Ritual Summon this card with 'Black Illusion Ritual'. Once per turn: You can target 1 monster your " \
        "opponent controls; equip that target to this card (max. 1). This card's ATK/DEF become equal to that equipped monster's. " \
        "If this card would be destroyed by battle, destroy that equipped monster instead. While equipped with that monster, " \
        "any battle damage you take from battles involving this card inflicts equal effect damage to your opponent.",
        "ATK": 0,
        "DEF": 0
    },
    { # Toon Mermaid
        "Name": "Toon Mermaid",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Toon, Effect",
        "Effect": "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand), while you control 'Toon World'. " \
        "Cannot attack the turn it is Special Summoned. You must pay 500 LP to declare an attack with this monster. If 'Toon World' on " \
        "the field is destroyed, destroy this card. Can attack your opponent directly, unless they control a Toon monster, in which case this card must target a Toon monster for its attacks.",
        "ATK": 1400,
        "DEF": 1500
    },
    { # Toon Summoned Skull
        "Name": "Toon Summoned Skull",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 6,
        "Type": "Fiend, Toon, Effect",
        "Effect": "(This card is always treated as an 'Archfiend' card.) Cannot be Normal Summoned/Set. Must first be Special Summoned " \
        "(from your hand) by Tributing 1 monster, while you control 'Toon World'. Cannot attack the turn it is Special Summoned. " \
        "You must pay 500 LP to declare an attack with this monster. If 'Toon World' on the field is destroyed, destroy this card. " \
        "Can attack your opponent directly, unless they control a Toon monster, in which case this card must target a Toon monster for its attacks.",
        "ATK": 1550,
        "DEF": 1400
    },
    { # Ameba
        "Name": "Ameba",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 1,
        "Type": "Aqua, Effect",
        "Effect": "When the control of this face-up card on the field shifts to your opponent, inflict 2000 points of damage to your opponent's Life Points. " \
        "This effect can only be used once as long as this card remains face-up on the field.",
        "ATK": 300,
        "DEF": 350
    },
    { # Giant Germ
        "Name": "Giant Germ",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Fiend, Effect",
        "Effect": "When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 WIND monster with 1500 or less ATK from your Deck, in face-up Attack Position.",
        "ATK": 1000,
        "DEF": 100
    },
    { # Giant Rat
        "Name": "Giant Rat",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast, Effect",
        "Effect": "When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 EARTH monster with 1500 or less ATK from your Deck, in Attack Position.",
        "ATK": 1400,
        "DEF": 1450
    },
    { # Karate Man
        "Name": "Karate Man",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Warrior, Effect",
        "Effect": "You can double the original ATK of this card once per turn. If you used this effect, destroy this card during the End Phase.",
        "ATK": 1000,
        "DEF": 1000
    },
    { # Mother Grizzly
        "Name": "Mother Grizzly",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Beast, Effect",
        "Effect": "When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 WATER monster with 1500 or less ATK from your Deck, in face-up Attack Position.",
        "ATK": 1400,
        "DEF": 1000
    },
    { # Mystic Tomato
        "Name": "Mystic Tomato",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Plant, Effect",
        "Effect": "When this card is destroyed by battle and sent to the GY: You can Special Summon 1 DARK monster with 1500 or less ATK from your Deck, in face-up Attack Position.",
        "ATK": 1400,
        "DEF": 1100
    },
    { # Nimble Momonga
        "Name": "Nimble Momonga",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Beast, Effect",
        "Effect": "When this card is destroyed by battle and sent to the Graveyard: Gain 1000 Life Points, then you can Special Summon any number of 'Nimble Momongas' from your Deck in face-down Defense Position.",
        "ATK": 1000,
        "DEF": 100
    },
    { # Senju of the Thousand Hands
        "Name": "Senju of the Thousand Hands",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Fairy, Effect",
        "Effect": "When this card is Normal or Flip Summoned: You can add 1 Ritual Monster from your Deck to your hand.",
        "ATK": 1400,
        "DEF": 1000
    },
    { # Shining Angel
        "Name": "Shining Angel",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 4,
        "Type": "Fairy, Effect",
        "Effect": "When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 LIGHT monster with 1500 or less ATK from your Deck, in face-up Attack Position.",
        "ATK": 1400,
        "DEF": 800
    },
    { # UFO Turtle
        "Name": "UFO Turtle",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 4,
        "Type": "Machine, Effect",
        "Effect": "When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 FIRE monster with 1500 or less ATK from your Deck, in face-up Attack Position.",
        "ATK": 1400,
        "DEF": 1200
    },
    { # Cyber Jar
        "Name": "Cyber Jar",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Rock, Flip, Effect",
        "Effect": "FLIP: Destroy all monsters on the field, then both players reveal the top 5 cards from their Decks, then Special Summon all revealed Level 4 or lower monsters in face-up Attack Position " \
        "or face-down Defense Position, also add any remaining cards to their hand. (If either player has less than 5 cards in their Deck, reveal as many as possible.)",
        "ATK": 900,
        "DEF": 900
    },
    { # Hiro's Shadow Scout
        "Name": "Hiro's Shadow Scout",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Fiend, Flip, Effect",
        "Effect": "FLIP: Your opponent draws 3 cards. Both players look at the cards. If there are any Spell Cards among them, discard all those Spell Card(s) to the Graveyard.",
        "ATK": 650,
        "DEF": 500
    },
    { # Manga Ryu-Ran
        "Name": "Manga Ryu-Ran",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 7,
        "Type": "Dragon, Toon, Effect",
        "Effect": "(This card is always treated as a 'Toon' card.) Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by Tributing 2 monsters, while you control 'Toon World'. " \
        "Cannot attack the turn it is Special Summoned. You must pay 500 LP to declare an attack with this monster. If 'Toon World' on the field is destroyed, destroy this card. " \
        "Can attack your opponent directly, unless they control a Toon monster, in which case this card must target a Toon monster for its attacks.",
        "ATK": 2200,
        "DEF": 2600
    },
    { # Blue-Eyes Toon Dragon
        "Name": "Blue-Eyes Toon Dragon",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 8,
        "Type": "Dragon, Toon, Effect",
        "Effect": "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by Tributing 2 monsters, while you control 'Toon World'. Cannot attack the turn it is Special Summoned. " \
        "You must pay 500 LP to declare an attack with this monster. If 'Toon World' on the field is destroyed, destroy this card. Can attack your opponent directly, unless they control a Toon monster, " \
        "in which case this card must target a Toon monster for its attacks.",
        "ATK": 3000,
        "DEF": 2500
    },
    { # Boar Soldier
        "Name": "Boar Soldier",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast-Warrior, Effect",
        "Effect": "If this card is Normal Summoned, destroy this card. If your opponent controls 1 or more monsters, decrease the ATK of this card by 1000 points.",
        "ATK": 2000,
        "DEF": 500
    },
    { # Ceremonial Bell
        "Name": "Ceremonial Bell",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Spellcaster, Effect",
        "Effect": "Both players must keep their hands revealed.",
        "ATK": 0,
        "DEF": 1850
    },
    { # Dark Zebra
        "Name": "Dark Zebra",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 4,
        "Type": "Beast, Effect",
        "Effect": "If this is the only Monster Card in your control during your Standby Phase, it is changed to Defense Position. You cannot change the position of this card during the same turn.",
        "ATK": 1800,
        "DEF": 400
    },
    { # Electric Snake
        "Name": "Electric Snake",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Thunder, Effect",
        "Effect": "When this card is discarded from your hand to the Graveyard by an effect of a card controlled by your opponent, draw 2 cards from your Deck.",
        "ATK": 800,
        "DEF": 900
    },
    { # Flash Assailant
        "Name": "Flash Assailant",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Fiend, Effect",
        "Effect": "Decrease the ATK and DEF of this card by 400 points for each card in your hand.",
        "ATK": 2000,
        "DEF": 2000
    },
    { # Griggle
        "Name": "Griggle",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 1,
        "Type": "Plant, Effect",
        "Effect": "When the control of this face-up card on the field shifts to your opponent, increase your Life Points by 3000 points. This effect can only be used once as long as this card remains face-up on the field.",
        "ATK": 350,
        "DEF": 300
    },
    { # Kotodama
        "Name": "Kotodama",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Fairy, Effect",
        "Effect": "If there are face-up monsters with the same name on the field, destroy those monsters. (If a monster is Summoned or flipped face-up that has the same name as a monster that is already face-up on the field, " \
        "the new face-up monster is destroyed. If they are Summoned or flipped face-up at the same time, they are all destroyed.)",
        "ATK": 0,
        "DEF": 1600
    },
    { # Minar
        "Name": "Minar",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 3,
        "Type": "Insect, Effect",
        "Effect": "When this card is discarded directly from your hand to the Graveyard by an effect of a card controlled by your opponent, inflict 1000 points of damage to your opponent's Life Points.",
        "ATK": 850,
        "DEF": 750
    },
    { # Penguin Knight
        "Name": "Penguin Knight",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 3,
        "Type": "Aqua, Effect",
        "Effect": "When this card is sent directly from your Deck to the Graveyard by an effect of a card controlled by your opponent, unite your Graveyard cards and your own Deck, shuffle them and form a new Deck.",
        "ATK": 900,
        "DEF": 800
    },
    { # Sonic Bird
        "Name": "Sonic Bird",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 4,
        "Type": "Winged Beast, Effect",
        "Effect": "When this card is Normal or Flip Summoned: You can add 1 Ritual Spell from your Deck to your hand.",
        "ATK": 1400,
        "DEF": 1000
    },
    { # Wall Shadow
        "Name": "Wall Shadow",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Warrior, Effect",
        "Effect": "Cannot be Normal Summoned/Set. Must first be Special Summoned with 'Magical Labyrinth'.",
        "ATK": 1600,
        "DEF": 3000
    },
    { # Spear Cretin
        "Name": "Spear Cretin",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Fiend, Flip, Effect",
        "Effect": "FLIP: When this card is sent to the Graveyard after being flipped, each player selects 1 monster from their Graveyard, " \
        "and Special Summons it in face-up Attack Position or face-down Defense Position.",
        "ATK": 500,
        "DEF": 500
    },
    { # Weather Report
        "Name": "Weather Report",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 4,
        "Type": "Aqua, Flip, Effect",
        "Effect": "FLIP: Destroys all of your opponent's face-up 'Swords of Revealing Light' on the field. If 'Swords of Revealing Light' is destroyed, " \
        "you can perform your Battle Phase twice this turn (or your next turn, if activated during your opponent's turn).",
        "ATK": 950,
        "DEF": 1500
    },
    { # Bladefly
        "Name": "Bladefly",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 2,
        "Type": "Insect, Effect",
        "Effect": "As long as this card remains face-up on the field, increase the ATK of all WIND monsters by 500 points and decrease the ATK of all EARTH monsters by 400 points.",
        "ATK": 600,
        "DEF": 700
    },
    { # Cannon Soldier
        "Name": "Cannon Soldier",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Machine, Effect",
        "Effect": "You can Tribute 1 monster; inflict 500 damage to your opponent.",
        "ATK": 1400,
        "DEF": 1300
    },
    { # Dark Elf
        "Name": "Dark Elf",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Spellcaster, Effect",
        "Effect": "This card requires a cost of 1000 of your own Life Points to attack.",
        "ATK": 2000,
        "DEF": 800
    },
    { # Great Moth
        "Name": "Great Moth",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 8,
        "Type": "Insect, Effect",
        "Effect": "This monster cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing 'Petit Moth' " \
        "during your 4th turn after 'Petit Moth' has been equipped with 'Cocoon of Evolution'.",
        "ATK": 2600,
        "DEF": 2500
    },
    { # Hoshiningen
        "Name": "Hoshiningen",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 2,
        "Type": "Fairy, Effect",
        "Effect": "All LIGHT monsters on the field gain 500 ATK, also all DARK monsters on the field lose 400 ATK.",
        "ATK": 500,
        "DEF": 700
    },
    { # Little Chimera
        "Name": "Little Chimera",
        "Category": "Monster",
        "Attribute": "FIRE",
        "Level": 2,
        "Type": "Beast, Effect",
        "Effect": "All FIRE monsters on the field gain 500 ATK. All WATER monsters on the field lose 400 ATK.",
        "ATK": 600,
        "DEF": 550
    },
    { # Masked Sorcerer
        "Name": "Masked Sorcerer",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Spellcaster, Effect",
        "Effect": "When this card inflicts Battle Damage to your opponent's Life Points, draw 1 card from your Deck.",
        "ATK": 900,
        "DEF": 1400
    },
    { # Milus Radiant
        "Name": "Milus Radiant",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 1,
        "Type": "Beast, Effect",
        "Effect": "As long as this card remains face-up on the field, increase the ATK of all EARTH monsters by 500 points and decrease the ATK of all WIND monsters by 400 points.",
        "ATK": 300,
        "DEF": 250
    },
    { # Muka Muka
        "Name": "Muka Muka",
        "Category": "Monster",
        "Attribute": "EARTH",
        "Level": 2,
        "Type": "Rock, Effect",
        "Effect": "This card gains 300 ATK and DEF for each card in your hand.",
        "ATK": 1400,
        "DEF": 1300
    },
    { # Sangan
        "Name": "Sangan",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 3,
        "Type": "Fiend, Effect",
        # Original effect, not the errata version
        "Effect": "When this card is sent from the field to the Graveyard, add 1 monster with 1500 or less ATK from your Deck to your hand.",
        "ATK": 1000,
        "DEF": 600
    },
    { # Shadow Ghoul
        "Name": "Shadow Ghoul",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 5,
        "Type": "Zombie, Effect",
        "Effect": "This card gains 100 ATK for each monster in your Graveyard.",
        "ATK": 1600,
        "DEF": 1300
    },
    { # Star Boy
        "Name": "Star Boy",
        "Category": "Monster",
        "Attribute": "WATER",
        "Level": 2,
        "Type": "Aqua, Effect",
        "Effect": "As long as this card remains face-up on the field, increase the ATK of all WATER monsters " \
        "by 500 points and decrease the ATK of all FIRE monsters by 400 points.",
        "ATK": 550,
        "DEF": 500
    },
    { # White Magical Hat
        "Name": "White Magical Hat",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 3,
        "Type": "Spellcaster, Effect",
        "Effect": "When this card inflicts Battle Damage to your opponent's Life Points, your opponent discards 1 card randomly from his/her hand.",
        "ATK": 1000,
        "DEF": 700
    },
    { # Witch's Apprentice
        "Name": "Witch's Apprentice",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Spellcaster, Effect",
        "Effect": "As long as this card remains face-up on the field, increase the ATK of all DARK monsters by 500 points and decrease the ATK of all LIGHT monsters by 400 points.",
        "ATK": 550,
        "DEF": 500
    },
    { # Witch of the Black Forest
        "Name": "Witch of the Black Forest",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 4,
        "Type": "Spellcaster, Effect",
        # Original effect, not the errata version
        "Effect": "When this card is sent from the field to the Graveyard: Add 1 monster with 1500 or less DEF from your Deck to your hand.",
        "ATK": 1100,
        "DEF": 1200
    },
    { # Magician of Faith
        "Name": "Magician of Faith",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 1,
        "Type": "Spellcaster, Flip, Effect",
        "Effect": "FLIP: Target 1 Spell in your GY; add that target to your hand.",
        "ATK": 300,
        "DEF": 400
    },
    { # Mask of Darkness
        "Name": "Mask of Darkness",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 2,
        "Type": "Fiend, Flip, Effect",
        "Effect": "FLIP: Target 1 Trap in your GY; add that target to your hand.",
        "ATK": 900,
        "DEF": 400
    },
    { # Princess of Tsurugi
        "Name": "Princess of Tsurugi",
        "Category": "Monster",
        "Attribute": "WIND",
        "Level": 3,
        "Type": "Warrior, Effect",
        "Effect": "FLIP: Inflict 500 damage to your opponent for each Spell and Trap Card on your opponent's side of the field.",
        "ATK": 900,
        "DEF": 700
    },
    { # Barrel Dragon
        "Name": "Barrel Dragon",
        "Category": "Monster",
        "Attribute": "DARK",
        "Level": 7,
        "Type": "Machine, Effect",
        "Effect": "Once per turn: You can target 1 monster your opponent controls; toss a coin 3 times and destroy it if at least 2 of the results are heads.",
        "ATK": 2600,
        "DEF": 2200
    },
    { # Time Wizard
        "Name": "Time Wizard",
        "Category": "Monster",
        "Attribute": "LIGHT",
        "Level": 2,
        "Type": "Spellcaster, Effect",
        "Effect": "Once per turn: You can toss a coin and call it. If you call it right, destroy all monsters your opponent controls. " \
        "If you call it wrong, destroy as many monsters you control as possible, and if you do, take damage equal to half the total ATK those destroyed monsters had while face-up on the field.",
        "ATK": 500,
        "DEF": 400
    },
    # Add more cards below using the same format
]